
"""
Master Product Schema Definition
All products must conform to this exact structure and field order.
"""

PRODUCT_SCHEMA = [
    "Product ID",
    "Product Name",
    "Brand",
    "Category",
    "Subcategory",
    "Barcode (EAN/UPC)",
    "Short Description",
    "Long Description",
    "Featured Image URL",
    "Gallery Image URLs",
    "Package Size",
    "Quantity",
    "Net Weight",
    "Volume for Liquids (ml/L)",
    "Carbon Footprint - kg CO₂e per pack",
    "Carbon Footprint - kg CO₂e per 100g/kg",
    "Carbon Grade (A-E)",
    "Color",
    "Ingredients List",
    "Storage Instructions",
    "Country of Origin",
    "Product Certifications",
    "Calories (kcal)",
    "Total Fat (g)",
    "Saturated Fat (g)",
    "Trans Fat (g)",
    "Monounsaturated Fat (g)",
    "Polyunsaturated Fat (g)",
    "Cholesterol (mg)",
    "Sodium (mg)",
    "Total Carbohydrates (g)",
    "Dietary Fiber (g)",
    "Total Sugars (g)",
    "Added Sugars (g)",
    "Protein (g)",
    "Water Content (%)",
    "Vitamin A (µg)",
    "Vitamin C (mg)",
    "Vitamin D (µg)",
    "Vitamin E (mg)",
    "Vitamin K (µg)",
    "Thiamine (Vitamin B1) (mg)",
    "Riboflavin (Vitamin B2) (mg)",
    "Niacin (Vitamin B3) (mg)",
    "Pantothenic Acid (Vitamin B5) (mg)",
    "Vitamin B6 (mg)",
    "Biotin (Vitamin B7) (µg)",
    "Folate (Vitamin B9) (µg)",
    "Vitamin B12 (µg)",
    "Calcium (mg)",
    "Iron (mg)",
    "Magnesium (mg)",
    "Phosphorus (mg)",
    "Potassium (mg)",
    "Zinc (mg)",
    "Copper (mg)",
    "Manganese (mg)",
    "Selenium (µg)",
    "Iodine (µg)",
    "Chromium (µg)",
    "Molybdenum (µg)",
    "Omega-3 Fatty Acids",
    "Omega-6 Fatty Acids",
    "Probiotics",
    "Prebiotics",
    "Antioxidant Content",
    "Polyphenols",
    "Adaptogens (Ashwagandha, etc.)",
    "Beta-glucans",
    "Curcumin (from Turmeric)",
    "Choline",
    "Vegan",
    "Vegetarian",
    "Gluten-Free",
    "Dairy-Free",
    "Soy-Free",
    "Nut-Free",
    "Egg-Free",
    "Shellfish-Free",
    "Kosher",
    "Halal",
    "Organic",
    "Non-GMO",
    "Low Carb",
    "Keto-Friendly",
    "Paleo-Friendly",
    "Whole30 Approved",
    "Low Sugar",
    "No Added Sugar",
    "Low Sodium",
    "High Fiber",
    "High Protein",
    "Heart Healthy",
    "Diabetes-Friendly",
    "Weight Management Friendly",
    "Contains Peanuts",
    "Contains Tree Nuts",
    "Contains Milk",
    "Contains Eggs",
    "Contains Wheat",
    "Contains Soybeans",
    "Contains Fish",
    "Contains Shellfish",
    "Contains Sesame",
    "Fortified with Vitamins/Minerals",
    "Cold-Pressed (for juices/oils)",
    "Grass-Fed (for meat/dairy)",
    "Pasture-Raised",
    "Wild-Caught (for fish)",
    "Fermented Product",
    "Sprouted Grains",
    "Allergens",
    "Tags",
    "Canned Food",
    "Non Canned Food",
    "No Preservatives",
    "Natural Ingredients",
    # Source tracking fields (added to every product)
    "Source Website Name",
    "Source Website URL",
    "Scraped At",
]

# Field type definitions for validation and inference
FIELD_TYPES = {
    # Boolean fields
    "boolean": [
        "Vegan", "Vegetarian", "Gluten-Free", "Dairy-Free", "Soy-Free",
        "Nut-Free", "Egg-Free", "Shellfish-Free", "Kosher", "Halal",
        "Organic", "Non-GMO", "Low Carb", "Keto-Friendly", "Paleo-Friendly",
        "Whole30 Approved", "Low Sugar", "No Added Sugar", "Low Sodium",
        "High Fiber", "High Protein", "Heart Healthy", "Diabetes-Friendly",
        "Weight Management Friendly", "Contains Peanuts", "Contains Tree Nuts",
        "Contains Milk", "Contains Eggs", "Contains Wheat", "Contains Soybeans",
        "Contains Fish", "Contains Shellfish", "Contains Sesame",
        "Fortified with Vitamins/Minerals", "Cold-Pressed (for juices/oils)",
        "Grass-Fed (for meat/dairy)", "Pasture-Raised", "Wild-Caught (for fish)",
        "Fermented Product", "Sprouted Grains", "Canned Food", "Non Canned Food",
        "No Preservatives", "Natural Ingredients"
    ],
    
    # Numeric fields
    "numeric": [
        "Quantity", "Net Weight", "Volume for Liquids (ml/L)",
        "Carbon Footprint - kg CO₂e per pack", "Carbon Footprint - kg CO₂e per 100g/kg",
        "Calories (kcal)", "Total Fat (g)", "Saturated Fat (g)", "Trans Fat (g)",
        "Monounsaturated Fat (g)", "Polyunsaturated Fat (g)", "Cholesterol (mg)",
        "Sodium (mg)", "Total Carbohydrates (g)", "Dietary Fiber (g)",
        "Total Sugars (g)", "Added Sugars (g)", "Protein (g)", "Water Content (%)",
        "Vitamin A (µg)", "Vitamin C (mg)", "Vitamin D (µg)", "Vitamin E (mg)",
        "Vitamin K (µg)", "Thiamine (Vitamin B1) (mg)", "Riboflavin (Vitamin B2) (mg)",
        "Niacin (Vitamin B3) (mg)", "Pantothenic Acid (Vitamin B5) (mg)",
        "Vitamin B6 (mg)", "Biotin (Vitamin B7) (µg)", "Folate (Vitamin B9) (µg)",
        "Vitamin B12 (µg)", "Calcium (mg)", "Iron (mg)", "Magnesium (mg)",
        "Phosphorus (mg)", "Potassium (mg)", "Zinc (mg)", "Copper (mg)",
        "Manganese (mg)", "Selenium (µg)", "Iodine (µg)", "Chromium (µg)",
        "Molybdenum (µg)"
    ],
    
    # List fields (arrays)
    "list": [
        "Gallery Image URLs", "Ingredients List", "Product Certifications",
        "Allergens", "Tags"
    ],
    
    # Text fields
    "text": [
        "Product ID", "Product Name", "Brand", "Category", "Subcategory",
        "Barcode (EAN/UPC)", "Short Description", "Long Description",
        "Featured Image URL", "Package Size", "Carbon Grade (A-E)", "Color",
        "Storage Instructions", "Country of Origin", "Omega-3 Fatty Acids",
        "Omega-6 Fatty Acids", "Probiotics", "Prebiotics", "Antioxidant Content",
        "Polyphenols", "Adaptogens (Ashwagandha, etc.)", "Beta-glucans",
        "Curcumin (from Turmeric)", "Choline", "Source Website Name",
        "Source Website URL", "Scraped At"
    ]
}

def get_empty_product():
    """Return a product dictionary with all fields set to None."""
    return {field: None for field in PRODUCT_SCHEMA}